import { chromium, devices } from '/Users/davidsonders/ro-bot/app/node_modules/playwright/index.mjs';
import fs from 'fs';
const O='/private/tmp/claude-501/-Users-davidsonders-ro-bot-app/502c56fe-c8cb-46e3-9c57-a296facb4678/scratchpad/real';
const ENV = Object.fromEntries(fs.readFileSync('/Users/davidsonders/ro-bot/app/__tests__/workflow/.env.test','utf8').split('\n').filter(l=>l.includes('=')&&!l.trim().startsWith('#')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^"|"$/g,'')];}));
const BASE = 'https://app.tenthgear.ai'; const KEY = ENV.VITE_FIREBASE_API_KEY;
async function login(role){ const r = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:ENV[`E2E_${role}_EMAIL`],password:ENV[`E2E_${role}_PASSWORD`],returnSecureToken:true})}); if(!r.ok) throw new Error('login '+role+' '+r.status); const j=await r.json(); return {token:j.idToken, uid:j.localId, email:j.email, refresh:j.refreshToken, expiresIn:+j.expiresIn}; }
async function api(tok, method, path, body){ const r = await fetch(BASE+path,{method,headers:{Authorization:'Bearer '+tok, ...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body!==undefined?JSON.stringify(body):undefined}); let d=null; try{ d=await r.json(); }catch{} return {status:r.status, data:d}; }
const log = (...a)=>console.log(...a);
const advisor = await login('ADVISOR'), tech = await login('TECH_A'), parts = await login('PARTS'), admin = await login('ADMIN');
const MODE = process.env.MODE || 'capture'; let roId = process.env.RO_ID ? Number(process.env.RO_ID) : null; const out = {heights:{}, desktopHeights:{}};
try {
  if (!roId) {
  const stamp = new Date().toISOString().replace(/[:.]/g,'-');
  const veh = await api(advisor.token,'POST','/api/vehicles',{make:'Honda',model:'Pilot',year:2021,vin:`E2E-VIN-${Date.now()}`,color:'Silver',licensePlate:'None',additionalDetails:''}); if (veh.status!==201) throw new Error('vehicle '+veh.status+' '+JSON.stringify(veh.data));
  const ro = await api(advisor.token,'POST','/api/repair-orders',{vehicleId:veh.data.id,customerName:'E2E Fixture',customerPhone:'555-0100',status:'open',mileage:84120,createdByRole:'advisor',dealerRoNumber:`E2E-Q-${stamp}`,saName:'PJ Macklin',skipPlaceholderIssue:true}); if (ro.status!==201) throw new Error('ro '+ro.status+' '+JSON.stringify(ro.data)); roId = ro.data.id; log('RO', roId);
  const issue = await api(advisor.token,'POST',`/api/repair-orders/${roId}/issues`,{customerComplaint:'Customer states fuel gauge reads empty after fill-up and engine cranks long before starting. Happens most mornings.',category:'recall'}); if (issue.status!==201) throw new Error('issue '+issue.status+' '+JSON.stringify(issue.data)); const issueId = issue.data.id;
  let r = await api(advisor.token,'PATCH',`/api/repair-orders/${roId}`,{assignedTechnicianId:tech.uid,workflowStatus:'assigned_to_tech'}); if (r.status!==200) throw new Error('assign '+r.status+' '+JSON.stringify(r.data));
  r = await api(tech.token,'PATCH',`/api/issues/${issueId}`,{cause:'Fuel pump module losing prime overnight; sender reads low. Matches recall bulletin.',correction:'Replace fuel pump module and sender per recall; clear codes; verify start and gauge.',laborHours:1.5}); if (r.status>=300) throw new Error('3c '+r.status+' '+JSON.stringify(r.data));
  r = await api(tech.token,'PATCH',`/api/repair-orders/${roId}`,{workflowStatus:'parts_pricing'}); if (r.status!==200) throw new Error('to parts '+r.status+' '+JSON.stringify(r.data));
  r = await api(parts.token,'POST',`/api/repair-orders/${roId}/take-over-parts`); if (r.status>=300) throw new Error('takeover '+r.status);
  r = await api(parts.token,'PATCH',`/api/issues/${issueId}`,{parts:[{id:`e2e-p1-${issueId}`,name:'Fuel pump module',quantity:1,partNumber:'RC-FP-002',price:null,inStock:null,partsNote:'Confirm the sender ships in the recall kit',customerApproved:true,deliveryState:'pending'},{id:`e2e-p2-${issueId}`,name:'Fuel level sender',quantity:1,partNumber:'RC-FS-011',price:null,inStock:true,customerApproved:true,deliveryState:'pending'}]}); if (r.status>=300) throw new Error('parts '+r.status+' '+JSON.stringify(r.data));
  log('seeded');
  }
  const b = await chromium.launch();


  if (MODE==='capture-admin') {
    if (process.env.CLOSE_ALSO) { for (const id of process.env.CLOSE_ALSO.split(',')) { const c = await api(admin.token,'PATCH',`/api/repair-orders/${id}`,{workflowStatus:'closed'}); log('closed', id, c.status); } }
    const ctx = await b.newContext({viewport:{width:1440,height:900}, deviceScaleFactor:2});
    const p2 = await ctx.newPage();
    await p2.goto(BASE+'/api/config');
    await p2.evaluate(async ({key, user}) => { await new Promise((res, rej) => { const req = indexedDB.open('firebaseLocalStorageDb', 1); req.onupgradeneeded = () => { req.result.createObjectStore('firebaseLocalStorage', {keyPath:'fbase_key'}); }; req.onsuccess = () => { const db = req.result; const tx = db.transaction('firebaseLocalStorage','readwrite'); tx.objectStore('firebaseLocalStorage').put({fbase_key:`firebase:authUser:${key}:[DEFAULT]`, value:{uid:user.uid,email:user.email,emailVerified:true,isAnonymous:false,providerData:[],stsTokenManager:{refreshToken:'',accessToken:user.token,expirationTime:Date.now()+50*60*1000},createdAt:String(Date.now()),lastLoginAt:String(Date.now()),apiKey:key,appName:'[DEFAULT]'}}); tx.oncomplete = () => { db.close(); res(); }; tx.onerror = () => rej(tx.error); }; req.onerror = () => rej(req.error); }); }, {key: KEY, user: {uid: admin.uid, email: admin.email, token: admin.token}});
    await p2.goto(BASE+'/'); await p2.waitForTimeout(3000);
    const openAdmin = async()=>{ await p2.goto(`${BASE}/repair-order/${roId}`); await p2.waitForSelector('[data-testid^="advisor-edit-pricing-"]', {timeout: 60000}); await p2.waitForTimeout(1500); await p2.evaluate(()=>document.fonts.ready); };
    const hideBar = async()=>{ await p2.evaluate(()=>{ const el=[...document.querySelectorAll('button,div')].find(e=>e.childElementCount<4 && /Hold to make a note/.test(e.textContent||'')); let f=el; while(f && getComputedStyle(f).position!=='fixed') f=f.parentElement; if(f) f.style.display='none'; document.querySelectorAll('button').forEach(b=>{ const cs=getComputedStyle(b); if(cs.position==='fixed' && b.getBoundingClientRect().bottom>window.innerHeight-120) b.style.display='none'; }); }); };
    const cardHandle = async()=>{ const btn = await p2.$('[data-testid^="advisor-edit-pricing-"]'); const h = await p2.evaluateHandle((b)=>{ let c=b; while(c && !(c.className||'').includes('bg-gray-300')) c=c.parentElement; return c; }, btn); return h.asElement(); };
    const measureCard = async()=>{ const c = await cardHandle(); const r = await c.boundingBox(); return {w: Math.round(r.width), h: Math.round(r.height)}; };
    // six-column read-only row (the parts page's shape, as P-1 ruled) built from the ledger rows' own data
    const sixcol = async(mode)=>{ await p2.evaluate((mode)=>{ const btn=document.querySelector('[data-testid^="advisor-edit-pricing-"]'); let card=btn; while(card && !(card.className||'').includes('bg-gray-300')) card=card.parentElement; const ul=card.querySelector('ul.divide-y'); if(!ul) return; const rows=[...ul.querySelectorAll(':scope > li')].map(li=>{ const name=li.querySelector('.font-semibold')?.textContent.trim()||''; const num=(li.querySelector('.font-mono')?.textContent||'').trim(); const badge=[...li.querySelectorAll('span')].map(s=>s.textContent.trim()).find(t=>/^(In stock|Not in stock)$/.test(t))||''; const note=li.querySelector('[data-testid="part-row-readonly-note"]')?.textContent.trim()||''; const qty=(li.querySelector('.w-9')?.textContent||'').trim().replace('×',''); const price=[...li.querySelectorAll('span')].map(s=>s.textContent.trim()).find(t=>/^\$|^—$/.test(t))||'—'; return {name,num,badge,note,qty,price}; });
      ul.style.display='none';
      const cell=(t,w,extra='')=>`<div style="width:${w}px;min-height:36px;border-radius:4px;background:#f8fafc;border:1px solid #f1f5f9;display:flex;align-items:center;padding:0 8px;font-size:14px;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;${extra}">${t}</div>`;
      const stock=(b)=>{ const on=b==='In stock'?'Yes':b==='Not in stock'?'No':'?'; const seg=(l)=>`<span style="flex:1;display:grid;place-items:center;font-size:13px;color:${l===on?(l==='Yes'?'#0f172a':'#fff'):'#4b5563'};background:${l===on?(l==='Yes'?'#78BC61':l==='No'?'#B9314F':'#64748b'):'#fff'};border-right:1px solid #e5e7eb;font-weight:${l===on?600:400}">${l}</span>`; return `<div style="display:inline-flex;width:164px;height:36px;border:1px solid #e5e7eb;border-radius:6px;overflow:hidden;background:#fff;opacity:.6">${seg('Yes')}${seg('No')}${seg('?')}</div>`; };
      const NOTE='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#0369a1" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align:middle;margin-left:6px"><path d="M16 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9z"/><path d="M15 3v6h6"/></svg>';
      const hdr='<div style="display:grid;grid-template-columns:152px 150px 164px 188px 66px 112px;gap:8px;padding-bottom:6px;font-size:10px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:#9ca3af"><span>Part #</span><span>Part Name</span><span>In Stock?</span><span>Note</span><span style="text-align:center">Qty</span><span style="text-align:right">Unit Price</span></div>';
      const body=rows.map(r=>{ const nameCell = cell(r.name + (mode==='mark' && r.note ? NOTE : ''),150); const noteCell = r.note ? cell(r.note,188,'border-color:#e2e8f0;background:#fff') : cell('<span style="color:#94a3b8">+ Note</span>',188,'border:1px dashed #cbd5e1;background:#fff'); const line = (mode==='line' && r.note) ? `<div style="display:flex;align-items:flex-start;gap:6px;padding:4px 0 2px 4px;font-size:12px;color:#4b5563;width:${152+150+164+188+66+112+40}px"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#9ca3af" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex:none;margin-top:2px"><path d="M16 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9z"/><path d="M15 3v6h6"/></svg><span>${r.note}</span></div>` : ''; return `<div style="display:grid;grid-template-columns:152px 150px 164px 188px 66px 112px;gap:8px;align-items:center;padding:3px 0">${cell(r.num,152)}${nameCell}${stock(r.badge)}${noteCell}${cell(r.qty,66,'justify-content:center')}${cell(r.price,112,'justify-content:flex-end;color:#94a3b8')}</div>${line}`; }).join('');
      const wrap=document.createElement('div'); wrap.style.cssText='overflow-x:auto;position:relative;'; wrap.innerHTML=`<div style="min-width:60rem">${hdr}${body}</div>`; ul.parentElement.insertBefore(wrap, ul);
      if (mode==='mark') { const panel=ul.parentElement; panel.style.position='relative'; const pop=document.createElement('div'); pop.style.cssText='position:absolute;left:190px;top:118px;width:230px;border-radius:8px;border:1px solid #e2e8f0;background:#fff;box-shadow:0 10px 30px rgba(0,0,0,.15);padding:8px 10px;font-size:12.5px;line-height:1.4;color:#334155;z-index:5'; pop.textContent=rows.find(r=>r.note)?.note||''; panel.appendChild(pop); }
      const hint=document.createElement('div'); hint.style.cssText='font-size:11px;color:#94a3b8;padding-top:4px'; hint.textContent='scrolls sideways →'; wrap.after(hint);
    }, mode); };
    await openAdmin(); await p2.screenshot({path:`${O}/pd-page.png`}); await hideBar(); await p2.screenshot({path:`${O}/pd-page.jpg`, type:'jpeg', quality:82});
    let c = await cardHandle(); await c.screenshot({path:`${O}/pd-today.png`}); await c.screenshot({path:`${O}/pd-today.jpg`, type:'jpeg', quality:85}); const m0 = await measureCard(); log('today card', JSON.stringify(m0));
    for (const mode of ['ruled','mark','line']) { await openAdmin(); await hideBar(); await sixcol(mode); await p2.waitForTimeout(300); c = await cardHandle(); await c.screenshot({path:`${O}/pd-${mode}.png`}); await c.screenshot({path:`${O}/pd-${mode}.jpg`, type:'jpeg', quality:85}); log(mode, JSON.stringify(await measureCard())); }
    fs.writeFileSync(O+'/admin-heights.json', JSON.stringify({today:m0}));
    await b.close();
    const cl = await api(admin.token,'PATCH',`/api/repair-orders/${roId}`,{workflowStatus:'closed'}); log('closed fixture RO', roId, cl.status); process.exit(0);
  }
  if (MODE==='inspect-admin') {
    const ctx = await b.newContext({viewport:{width:1440,height:900}, deviceScaleFactor:2});
    const p2 = await ctx.newPage();
    await p2.goto(BASE+'/api/config');
    await p2.evaluate(async ({key, user}) => { await new Promise((res, rej) => { const req = indexedDB.open('firebaseLocalStorageDb', 1); req.onupgradeneeded = () => { req.result.createObjectStore('firebaseLocalStorage', {keyPath:'fbase_key'}); }; req.onsuccess = () => { const db = req.result; const tx = db.transaction('firebaseLocalStorage','readwrite'); tx.objectStore('firebaseLocalStorage').put({fbase_key:`firebase:authUser:${key}:[DEFAULT]`, value:{uid:user.uid,email:user.email,emailVerified:true,isAnonymous:false,providerData:[],stsTokenManager:{refreshToken:'',accessToken:user.token,expirationTime:Date.now()+50*60*1000},createdAt:String(Date.now()),lastLoginAt:String(Date.now()),apiKey:key,appName:'[DEFAULT]'}}); tx.oncomplete = () => { db.close(); res(); }; tx.onerror = () => rej(tx.error); }; req.onerror = () => rej(req.error); }); }, {key: KEY, user: {uid: admin.uid, email: admin.email, token: admin.token}});
    await p2.goto(BASE+'/'); await p2.waitForTimeout(3000);
    await p2.goto(`${BASE}/repair-order/${roId}`); await p2.waitForSelector('[data-testid^="advisor-edit-pricing-"]', {timeout: 60000}); await p2.waitForTimeout(1500);
    const info = await p2.evaluate(()=>{ const btn=document.querySelector('[data-testid^="advisor-edit-pricing-"]'); let card=btn; while(card && !(card.className||'').includes('bg-gray-300')) card=card.parentElement; if(!card) return {err:'no card'}; const c=card.cloneNode(true); c.querySelectorAll('svg').forEach(e=>e.replaceWith('<svg/>')); const blocks=[]; const walk=(el,depth)=>{ if(depth>5) return; [...el.children].forEach(ch=>{ const r=ch.getBoundingClientRect(); if(r.height>=16) blocks.push({depth, tag:ch.tagName, cls:(ch.className||'').toString().slice(0,90), h:Math.round(r.height), w:Math.round(r.width), text:(ch.textContent||'').trim().slice(0,40)}); walk(ch,depth+1); }); }; walk(card,0); return {html:c.outerHTML, blocks, rect:card.getBoundingClientRect().toJSON()}; });
    fs.writeFileSync(O+'/admin-card.html', info.html||''); fs.writeFileSync(O+'/admin-blocks.json', JSON.stringify(info.blocks||[],null,1));
    const btn = await p2.$('[data-testid^="advisor-edit-pricing-"]'); const card = await p2.evaluateHandle((b)=>{ let c=b; while(c && !(c.className||'').includes('bg-gray-300')) c=c.parentElement; return c; }, btn);
    await card.asElement().screenshot({path:O+'/pd-today.png'});
    await p2.screenshot({path:O+'/pd-page.png'});
    log('admin card', JSON.stringify(info.rect), 'RO', roId); await b.close(); process.exit(0);
  }
  async function session(viewport, mobile){
    const ctx = await b.newContext({viewport, deviceScaleFactor:2, isMobile:mobile, hasTouch:mobile, userAgent: mobile ? devices['iPhone 13'].userAgent : undefined});
    const p = await ctx.newPage();
    await p.goto(BASE+'/api/config'); 
    await p.evaluate(async ({key, user}) => { await new Promise((res, rej) => { const req = indexedDB.open('firebaseLocalStorageDb', 1); req.onupgradeneeded = () => { req.result.createObjectStore('firebaseLocalStorage', {keyPath:'fbase_key'}); }; req.onsuccess = () => { const db = req.result; const tx = db.transaction('firebaseLocalStorage','readwrite'); tx.objectStore('firebaseLocalStorage').put({fbase_key:`firebase:authUser:${key}:[DEFAULT]`, value:{uid:user.uid,email:user.email,emailVerified:true,isAnonymous:false,providerData:[],stsTokenManager:{refreshToken:'',accessToken:user.token,expirationTime:Date.now()+50*60*1000},createdAt:String(Date.now()),lastLoginAt:String(Date.now()),apiKey:key,appName:'[DEFAULT]'}}); tx.oncomplete = () => { db.close(); res(); }; tx.onerror = () => rej(tx.error); }; req.onerror = () => rej(req.error); }); }, {key: KEY, user: {uid: parts.uid, email: parts.email, token: parts.token}});
    await p.goto(BASE+'/'); await p.waitForTimeout(3000);
    return p;
  }
  const CARD = '[data-testid="parts-line-card-has-parts"]';
  async function openRO(p){ await p.goto(`${BASE}/parts/repair-order/${roId}`); await p.waitForSelector(CARD, {timeout: 60000}); await p.waitForTimeout(1500); await p.evaluate(()=>document.fonts.ready); }
  async function measure(p){ return await p.evaluate((sel)=>Math.round(document.querySelector(sel).getBoundingClientRect().height), CARD); }
  const VARIANTS = {
    today: async()=>{},
    pad: async(p)=>{ await p.addStyleTag({content:`${CARD} > div:first-child{padding:12px 12px 8px !important} ${CARD} .p-6.space-y-3.pt-0{padding:0 12px 12px !important} ${CARD} .space-y-3 > * + *{margin-top:8px !important} ${CARD} .grid.grid-cols-1.gap-3{gap:8px !important} ${CARD} .p-3{padding:8px !important} ${CARD} .gap-2{gap:6px !important}`}); },
    cc: async(p)=>{ await p.evaluate((sel)=>{ document.querySelectorAll(sel+' *').forEach(el=>{ const cs=getComputedStyle(el); if (cs.webkitLineClamp==='2') { el.style.webkitLineClamp='1'; } }); }, CARD); },
    rail: async(p)=>{ await p.evaluate(()=>{ const lbl=[...document.querySelectorAll('div')].find(e=>/^Parts Needed/.test(e.textContent.trim()) && e.textContent.trim().length<20 && e.className.includes('font-semibold')); if(!lbl) return; const row=lbl.closest('.justify-between'); row.style.display='none'; const panel=row.parentElement; panel.style.position='relative'; panel.style.setProperty('padding-left','36px','important'); const rail=document.createElement('div'); rail.style.cssText='position:absolute;left:0;top:0;bottom:0;width:24px;background:#f8fafc;border-right:1px solid #e2e8f0;border-radius:8px 0 0 8px;display:flex;align-items:center;justify-content:center;'; const s=document.createElement('span'); s.textContent=lbl.textContent.trim().replace(/(\d+)$/,'· $1'); s.style.cssText='writing-mode:vertical-rl;transform:rotate(180deg);font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:#64748b;white-space:nowrap;'; rail.appendChild(s); panel.appendChild(rail); }); },
    notes: async(p)=>{ await p.evaluate(()=>{ const lbl=[...document.querySelectorAll('div,span,h4,label')].find(e=>e.childElementCount===0 && e.textContent.trim()==='Parts notes'); if(!lbl) return; const tile=lbl.closest('.rounded-lg'); [...tile.children].forEach(ch=>{ if(!ch.contains(lbl)) ch.style.display='none'; }); tile.style.minHeight='44px'; tile.style.flexDirection='row'; tile.style.alignItems='center'; tile.style.justifyContent='space-between'; const hint=document.createElement('span'); hint.textContent='Add a note ›'; hint.style.cssText='font-size:13px;color:#94a3b8;'; tile.appendChild(hint); }); },
    onerow: async(p)=>{ await p.evaluate(()=>{ const wide=document.querySelector('.min-w-\\[60rem\\]'); if(!wide) return; const hdr=wide.querySelector(':scope > .grid'); if(hdr) hdr.style.display='none'; wide.querySelectorAll('ul > li').forEach(li=>{ const grid=li.querySelector('.grid.items-center'); if(!grid) return; const num=grid.querySelector('input[data-testid^="part-row-part-number"]')?.value||''; const name=grid.querySelector('input[data-testid^="part-row-name"]')?.value||''; const qty=grid.querySelector('input[data-testid^="part-row-qty"]')?.value||''; const stockBtn=[...grid.querySelectorAll('button[data-testid^="part-row-stock-"]')].find(b=>/bg-brand|bg-slate-500/.test(b.className)); const stock=stockBtn?stockBtn.textContent.trim():'?'; grid.style.display='none'; const row=document.createElement('div'); row.style.cssText='display:flex;align-items:center;gap:10px;min-height:28px;font-size:13px;color:#0f172a;'; row.innerHTML='<span style="font-family:ui-monospace,Menlo,monospace;color:#475569">'+num+'</span><span style="flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+name+'</span><span style="font-size:11px;color:#6b7280">×'+qty+'</span><span style="font-size:11px;font-weight:600;border-radius:4px;padding:1px 7px;background:'+(stock==='Yes'?'#78BC61':stock==='No'?'#B9314F':'#64748b')+';color:'+(stock==='Yes'?'#0f172a':'#fff')+'">'+stock+'</span>'; row.style.maxWidth=(wide.closest('.overflow-x-auto').clientWidth)+'px'; li.firstElementChild.prepend(row); }); }); },
  };
  VARIANTS.compact = async(p)=>{ await VARIANTS.pad(p); await VARIANTS.cc(p); await VARIANTS.notes(p); await VARIANTS.onerow(p); await p.evaluate(()=>{ const lbl=[...document.querySelectorAll('div')].find(e=>/^Parts Needed/.test(e.textContent.trim()) && e.textContent.trim().length<20 && e.className.includes('font-semibold')); if(lbl){ const chip=document.createElement('span'); chip.textContent='Compact'; chip.style.cssText='margin-left:auto;font-size:10px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:#475569;border:1px solid #cbd5e1;border-radius:4px;padding:2px 6px;background:#f8fafc;'; lbl.closest('.justify-between').appendChild(chip); } }); };
  // Dave's combination (9/9): ① tighter padding + the top row as FOUR columns 30/30/20/20 (Parts counter notes · Story Notes · Complaint · Cause) + ③ the rail
  VARIANTS.fourcol = async(p)=>{ await p.evaluate((sel)=>{ const card=document.querySelector(sel); const grid=[...card.querySelectorAll('.grid')].find(g=>/grid-cols-1/.test(g.className) && /md:grid-cols-3/.test(g.className)); if(!grid) return; grid.style.gridTemplateColumns='3fr 3fr 2fr 2fr'; const third=grid.children[2]; if(third && third.classList.contains('grid')) third.style.display='contents'; }, CARD); };
  VARIANTS.dave = async(p)=>{ await VARIANTS.pad(p); await VARIANTS.fourcol(p); await VARIANTS.rail(p); };
  // Dave 9/9 v2: notes tile keeps today's width (1/3); Story Notes · Complaint · Cause split the rest equally; COMPLAINT/CAUSE labels inline
  VARIANTS.fourcol2 = async(p)=>{ await p.evaluate((sel)=>{ const card=document.querySelector(sel); const grid=[...card.querySelectorAll('.grid')].find(g=>/grid-cols-1/.test(g.className) && /md:grid-cols-3/.test(g.className)); if(!grid) return; grid.style.gridTemplateColumns='3fr 2fr 2fr 2fr'; const third=grid.children[2]; if(third && third.classList.contains('grid')) third.style.display='contents';
    ['Complaint','Cause'].forEach(name=>{ const lbl=[...card.querySelectorAll('*')].find(e=>e.childElementCount===0 && e.textContent.trim()===name); if(!lbl) return; const tile=lbl.parentElement; tile.style.display='block'; lbl.style.display='block'; lbl.style.marginBottom='4px'; const txt=lbl.nextElementSibling; if(txt){ txt.style.display='-webkit-box'; txt.style.webkitLineClamp='2'; txt.style.webkitBoxOrient='vertical'; txt.style.overflow='hidden'; } }); }, CARD); };
  VARIANTS.dave = async(p)=>{ await VARIANTS.pad(p); await VARIANTS.fourcol2(p); await VARIANTS.rail(p); };
  // Parts users work on DESKTOP (Dave 9/9) — capture there. 1440×900 is the common shop monitor size.
  const d = await session({width:1440,height:900}, false);
  for (const [k, apply] of Object.entries(VARIANTS).filter(([k])=>['today','dave'].includes(k))) {
    await openRO(d); await apply(d); await d.waitForTimeout(400);
    out.desktopHeights[k] = await measure(d);
    const card = await d.$(CARD);
    await card.screenshot({path:`${O}/qd-${k}.png`}); await card.screenshot({path:`${O}/qd-${k}.jpg`, type:'jpeg', quality:82});
    if (k==='today') { await d.screenshot({path:`${O}/qd-today-viewport.jpg`, type:'jpeg', quality:80}); }
    log(k, out.desktopHeights[k]);
  }
  await d.context().close(); await b.close();
  fs.writeFileSync(O+'/heights.json', JSON.stringify(out, null, 1)); log(JSON.stringify(out));
} finally {
  if (roId && MODE!=='inspect' && !process.env.KEEP) { const c = await api(admin.token,'PATCH',`/api/repair-orders/${roId}`,{workflowStatus:'closed'}); log('closed fixture RO', roId, c.status); }
}
