import { chromium } from '/Users/davidsonders/ro-bot/app/node_modules/playwright/index.mjs';
import fs from 'fs';
const S='/Users/davidsonders/.claude/skills/groom/phone-board';
fs.writeFileSync(S+'/local.html', '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0">' + fs.readFileSync(S+'/grooming-board-phone.html','utf8') + '</body></html>');
const b = await chromium.launch(); const errors=[];
const p = await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2})).newPage(); p.on('pageerror', e=>errors.push(String(e)));
await p.goto('file://'+S+'/local.html#/item/Q'); await p.waitForTimeout(800);
console.log('phone Q', await p.evaluate(()=>({w: document.documentElement.scrollWidth, imgs: document.querySelectorAll('.m-gallery img').length, first: document.querySelector('.m-gallery img')?.getBoundingClientRect().height|0})));
await p.evaluate(()=>document.querySelector('.m-gallery').scrollIntoView()); await p.screenshot({path:S+'/tq-phone.png', fullPage:false});
const d = await (await b.newContext({viewport:{width:1280,height:900}})).newPage(); d.on('pageerror', e=>errors.push(String(e)));
await d.goto('file://'+S+'/local.html#/item/Q'); await d.waitForTimeout(800);
await d.evaluate(()=>document.querySelector('.m-gallery').scrollIntoView()); await d.screenshot({path:S+'/tq-desk.png', fullPage:false});
console.log('desk Q', await d.evaluate(()=>({w: document.documentElement.scrollWidth, imgs: document.querySelectorAll('.m-gallery img').length})));
console.log('ERRORS', JSON.stringify(errors)); await b.close();
