import { chromium } from '/Users/davidsonders/ro-bot/app/node_modules/playwright/index.mjs';
import fs from 'fs';
const S='/Users/davidsonders/.claude/skills/groom/phone-board';
fs.writeFileSync(S+'/local.html', '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0">' + fs.readFileSync(S+'/grooming-board-phone.html','utf8') + '</body></html>');
const b = await chromium.launch(); const p = await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage();
const errors=[]; p.on('pageerror', e=>errors.push(String(e)));
await p.goto('file://'+S+'/local.html#/item/Q'); await p.evaluate(()=>localStorage.clear()); await p.reload(); await p.waitForTimeout(500);
console.log('Q', await p.evaluate(()=>({h: document.body.scrollHeight, scrollW: document.documentElement.scrollWidth, btns: [...document.querySelectorAll('[data-stage]')].map(b=>b.textContent), lbl: document.querySelector('.m-stage-lbl').textContent, ph: document.getElementById('note-field').placeholder, fields: document.querySelectorAll('textarea').length, decs: document.querySelectorAll('.m-dec').length})));
await p.screenshot({path:S+'/t6-Q.png', fullPage:true});
await p.click('button[data-stage="keep"]'); await p.waitForTimeout(300);
console.log('after keep', await p.evaluate(()=>({rl: document.getElementById('rl-stage').textContent, strip: document.getElementById('stage-block').className})));
await p.fill('#note-field', 'Show me the real card height first.'); await p.waitForTimeout(900);
console.log('hint', await p.evaluate(()=>document.getElementById('note-hint').textContent));
await p.goto('file://'+S+'/local.html#/item/SA-20b'); await p.waitForTimeout(400);
console.log('SA-20b', await p.evaluate(()=>({h: document.body.scrollHeight, scrollW: document.documentElement.scrollWidth})));
await p.screenshot({path:S+'/t6-SA20b.png', fullPage:true});
await p.goto('file://'+S+'/local.html#/item/U'); await p.waitForTimeout(400);
console.log('U feedback label', await p.evaluate(()=>document.getElementById('note-field').previousElementSibling.textContent+' | ph="'+document.getElementById('note-field').placeholder+'"'));
await p.goto('file://'+S+'/local.html#/'); await p.reload(); await p.waitForTimeout(400);
console.log('dash', await p.evaluate(()=>({hero: document.querySelector('.m-total').textContent, q: document.querySelector('a.m-row[href="#/item/Q"]').textContent})));
console.log('ERRORS', JSON.stringify(errors)); await b.close();
