import { chromium } from '/Users/davidsonders/ro-bot/app/node_modules/playwright/index.mjs';
import fs from 'fs';
const S='/Users/davidsonders/.claude/skills/groom/phone-board';
fs.writeFileSync(S+'/local.html', '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0">' + fs.readFileSync(S+'/grooming-board-phone.html','utf8') + '</body></html>');
const b = await chromium.launch(); const p = await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true})).newPage();
const errors=[]; p.on('pageerror', e=>errors.push(String(e)));
await p.goto('file://'+S+'/local.html#/'); await p.evaluate(()=>localStorage.clear()); await p.reload(); await p.waitForTimeout(400);
console.log('hero', await p.evaluate(()=>document.querySelector('.m-total').textContent));
console.log('Q row', await p.evaluate(()=>document.querySelector('a.m-row[href="#/item/Q"]').textContent));
await p.screenshot({path:S+'/t5-dash.png', fullPage:false});
await p.goto('file://'+S+'/local.html#/item/Q'); await p.waitForTimeout(400);
await p.screenshot({path:S+'/t5-Q.png', fullPage:true});
await p.evaluate(()=>window.scrollTo(0,300)); const y0 = await p.evaluate(()=>window.scrollY);
await p.click('button[data-stage="advance"]'); await p.waitForTimeout(300);
console.log('stage', await p.evaluate(()=>({rl: document.getElementById('rl-stage').textContent, y: window.scrollY})), 'y0', y0);
await p.fill('[data-note-mirror]', 'How tall is the card on a real RO today?'); await p.waitForTimeout(900);
console.log('mirror→bottom', await p.evaluate(()=>document.getElementById('note-field').value));
await p.fill('#note-field', 'How tall is the card on a real RO today? And on desktop?'); await p.waitForTimeout(900);
console.log('bottom→mirror', await p.evaluate(()=>document.querySelector('[data-note-mirror]').value));
await p.goto('file://'+S+'/local.html#/'); await p.reload(); await p.waitForTimeout(400);
console.log('after advance', await p.evaluate(()=>({hero: document.querySelector('.m-total').textContent, q: document.querySelector('a.m-row[href="#/item/Q"]').textContent})));
await p.goto('file://'+S+'/local.html#/item/SA-6b'); await p.waitForTimeout(300);
console.log('groomed stage line', await p.evaluate(()=>document.querySelector('.m-stage-lbl').textContent));
console.log('ERRORS', JSON.stringify(errors)); await b.close();
